In [1]:
import numpy as np

In [2]:
X= [1,3,7,9]

In [5]:
print (X)

[1, 3, 7, 9]


In [6]:
Array_J= np.array ([
[4,6,7,9],
[2,7,9,2],
[5,8,3,4]
])

In [8]:
print (Array_J)

[[4 6 7 9]
 [2 7 9 2]
 [5 8 3 4]]


In [9]:
Array_J.dtype

dtype('int64')

In [12]:
Array_str= np.array ([
[4,6,7,9],
[2,7,9,2],
[5,8,3,4]
], dtype='str')

In [13]:
Array_str

array([['4', '6', '7', '9'],
       ['2', '7', '9', '2'],
       ['5', '8', '3', '4']], dtype='<U1')

In [14]:
Array_str.size

12

In [16]:
Array_str.shape

(3, 4)

In [18]:
Array_str.ndim

2

In [33]:
#Array construction

In [27]:
ArrayZeros = np.zeros ((5,4), dtype='int')

In [28]:
ArrayZeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
ArrayOnes = np.ones ((5,4), dtype='int')

In [32]:
ArrayOnes

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
ArrayFull= np.full((5,4), 7, dtype='int')

In [48]:
ArrayFull

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [49]:
ArrayFullX= np.full((5,4), 'X')

In [50]:
ArrayFullX

array([['X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X']], dtype='<U1')

In [51]:
ArrayZeros+ArrayOnes

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
ArrayOnes+ArrayFull

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])