In [25]:
import numpy as np

In [18]:
x1=np.array([1,2,3,4,5,6])

In [19]:
x1

array([1, 2, 3, 4, 5, 6])

In [20]:
x2=np.array([[2,3,7,4,8,9,8,3,8,1], [7,9,4,7,7,1,3,3,7,4]])

In [21]:
x2

array([[2, 3, 7, 4, 8, 9, 8, 3, 8, 1],
       [7, 9, 4, 7, 7, 1, 3, 3, 7, 4]])

In [22]:
x3= np.array ([[1,2,3], [4,5,6], [7,8,9]])

In [23]:
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print (x1)

print (x2)

print (x3)

[1 2 3 4 5 6]
[[2 3 7 4 8 9 8 3 8 1]
 [7 9 4 7 7 1 3 3 7 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
randNum= np.random.randint(low=2, high=122,size=8)

In [40]:
randNum

array([115,  87, 117,  69,  73,  78,  23,  26])

In [ ]:
random_2= np.random.randint(low=50, high=101, size=(6,))
print(random_integers_between_50_and_100)